[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = [
  "npm install -g npm@latest",
  "npm install"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "npx serve -s dist -l 8080"

[variables]
NODE_ENV = "production"
