version: 2
updates:
  # Client dependencies
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "ismaelmours"
    assignees:
      - "ismaelmours"
    commit-message:
      prefix: "chore(client)"
      include: "scope"

  # Server dependencies
  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "ismaelmours"
    assignees:
      - "ismaelmours"
    commit-message:
      prefix: "chore(server)"
      include: "scope"

  # Worker dependencies
  - package-ecosystem: "npm"
    directory: "/worker"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "ismaelmours"
    assignees:
      - "ismaelmours"
    commit-message:
      prefix: "chore(worker)"
      include: "scope"

  # Common dependencies
  - package-ecosystem: "npm"
    directory: "/common"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "ismaelmours"
    assignees:
      - "ismaelmours"
    commit-message:
      prefix: "chore(common)"
      include: "scope"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "ismaelmours"
    assignees:
      - "ismaelmours"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/server"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "ismaelmours"
    assignees:
      - "ismaelmours"
    commit-message:
      prefix: "chore(docker)"
      include: "scope"
