[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = [
  "cd server && npm install"
]

[phases.build]
cmds = [
  "cd server && npm run build"
]

[start]
cmd = "cd server && node dist/index.js"

[variables]
NODE_ENV = "production"
