apiVersion: v1
kind: Secret
metadata:
  name: echoboard-secrets
  namespace: echoboard-dev
type: Opaque
data:
  # Base64 encoded values - replace with your actual values
  # To encode: echo -n "your-value" | base64
  mongo-uri: bW9uZ29kYjovL21vbmdvYi1zcnY6MjcwMTcvZWNob2JvYXJk  # mongodb://mongodb-srv:27017/echoboard
  jwt-key: eW91ci1zdXBlci1zZWNyZXQtanN3LWtleS1oZXJl  # your-super-secret-jwt-key-here
  redis-password: ""  # Empty for no password
  resend-api-key: cmVfQWFVdnRTMXBfTlg3RVk1ZlQ4OHV2MThxYjFVbkNuaTV4  # re_AaUvtS1p_NX7EY5fT88uv18qb1UnCni5x
