apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-depl
  namespace: echoboard-dev
  labels:
    app: server
    environment: development
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
        environment: development
    spec:
      containers:
        - name: server
          image: ismaelmours/echoboard-server:latest
          imagePullPolicy: Always
          env:
            - name: NODE_ENV
              value: 'production'
            - name: PORT
              value: '3000'
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: echoboard-secrets
                  key: mongo-uri
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: echoboard-secrets
                  key: jwt-key
            - name: REDIS_HOST
              value: 'redis-srv'
            - name: REDIS_PORT
              value: '6379'
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: echoboard-secrets
                  key: redis-password
                  optional: true
            - name: RESEND_API_KEY
              valueFrom:
                secretKeyRef:
                  name: echoboard-secrets
                  key: resend-api-key
            - name: FROM_EMAIL
              value: 'EchoBoard <noreply@resend.dev>'
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: server-srv
  namespace: echoboard-dev
  labels:
    app: server
    environment: development
spec:
  selector:
    app: server
  ports:
    - name: server
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
