apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: echoboard/server
          imagePullPolicy: Never
          env:
            - name: MONGO_URI
              value: 'mongodb://host.docker.internal:27017/echoboard'
            - name: JWT_KEY
              value: 'your-super-secret-jwt-key-here'
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: 'echoboard'
            - name: NATS_CLIENT_ID
              value: 'server'
            - name: REDIS_HOST
              value: 'redis-srv'
            - name: REDIS_PORT
              value: '6379'
            - name: RESEND_API_KEY
              value: 're_AaUvtS1p_NX7EY5fT88uv18qb1UnCni5x'
            - name: FROM_EMAIL
              value: 'EchoBoard <noreply@resend.dev>'
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: server-srv
spec:
  selector:
    app: server
  ports:
    - name: server
      protocol: TCP
      port: 3000
      targetPort: 3000